# Generated by Django 5.0 on 2024-02-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
