# Generated by Django 5.0 on 2024-02-25 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_paid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Session_ID in Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Плательщик'),
        ),
    ]
